<?xml version="1.0" encoding="UTF-8"?>
<DwgData>
<DwgEntity type="IAcad3DPolyline" id="000000002b0ef258" desc="IAcad3DPolyline: AutoCAD 3dPolyline Interface" Application="IAcadApplication 000000013ffc2308" Closed="0" Coordinate="...Indexed contents not shown..." Coordinates="(21.4409 14.6498 0.0 20.8962 5.65378 0.0 ... )" Document="IAcadDocument 00000000352edf58" EntityTransparency="ByLayer" Handle="1C1" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 0000000035d01f18" Layer="0" Length="38.6446" Linetype="ByLayer" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" ObjectID="56" ObjectID32="56" ObjectName="AcDb3dPolyline" OwnerID="57" OwnerID32="57" PlotStyleName="ByLayer" TrueColor="IAcadAcCmColor 0000000035d01bb0" Type="0" Visible="-1" />
</DwgData>